apiVersion: apps/v1
kind: Deployment
metadata:
  name: shotgrid-transmitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shotgrid-transmitter
  template:
    metadata:
      labels:
        app: shotgrid-transmitter
    spec:
      hostAliases:
        - ip: "192.168.100.240"
          hostnames:
            - "ayon.d2-india.com"
      containers:
      - name: transmitter
        image: balajidd/ayon-shotgrid-transmitter:0.6.1
        env:
        - name: REQUESTS_CA_BUNDLE
          value: "/certs/tls.crt"
        - name: AYON_API_KEY
          valueFrom:
            secretKeyRef:
              name: shotgrid-secret
              key: AYON_API_KEY
        - name: AYON_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: shotgrid-config
              key: AYON_SERVER_URL
        - name: AYON_ADDON_NAME
          valueFrom:
            configMapKeyRef:
              name: shotgrid-config
              key: AYON_ADDON_NAME
        - name: AYON_ADDON_VERSION
          valueFrom:
            configMapKeyRef:
              name: shotgrid-config
              key: AYON_ADDON_VERSION

        volumeMounts:
          - name: tls-volume
            mountPath: /certs
            readOnly: true
      volumes:
        - name: tls-volume
          secret:
            secretName: ayon-tls
